name: Build and Deploy Multiple Sites

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        site: [site1, site2, site3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for ${{ matrix.site }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/myapp-${{ matrix.site }}:latest
            ${{ secrets.DOCKER_USERNAME }}/myapp-${{ matrix.site }}:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_CONFIG=${{ matrix.site }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
